name: solana_wallet_provider
description: Provider widget for solana_web3 and solana_wallet_adapter packages.
version: 0.1.8
publish_to: none

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^4.1.0
  async: ^2.10.0
  shared_preferences: ^2.1.0
  synchronized: ^3.1.0

  solana_common: ^0.1.0+1
  solana_web3: ^0.1.2
  solana_jsonrpc: ^0.0.1
  solana_wallet_adapter_platform_interface: ^0.0.6
  solana_wallet_adapter_web: ^0.0.9
  solana_wallet_provider:
    git:
      url: https://github.com/kingfariz/solana-web3.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  assets:
    - icons/
  # plugin:
  #   platforms:
  #     android:
  #       default_package: solana_wallet_adapter_android
  #     ios:
  #       default_package: solana_wallet_adapter_ios
  #     web:
  #       default_package: solana_wallet_adapter_web
